defaults:
  - liam_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1.1e7
NUM_ENVS: 256
LR: 0.003
ENCODER_DECODER_LR: 7e-3
ENT_COEF: 0.01
CLIP_EPS: 0.05
ANNEAL_LR: false
UPDATE_EPOCHS: 5
ENCODER_HIDDEN_DIM: 128
ENCODER_OUTPUT_DIM: 20 # Embedding dimension
DECODER_HIDDEN_DIM: 128
POLICY_INPUT_DIM: 20 # Embedding dimension + observation dimension (obs dim added in the run script)