defaults:
  - open_ended_fcp/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 3e6
NUM_OPEN_ENDED_ITERS: 20
LR: 1e-3
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 8
CLIP_EPS: 0.1
ENT_COEF: 0.05
