defaults:
  - task: overcooked/cramped_room # task configs
  - hydra: hydra_simple
  - _self_

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
TASK_NAME: ${task.TASK_NAME}

EVAL_SEED: 34957
MAX_EPISODE_STEPS: ${task.ROLLOUT_LENGTH}
NUM_EVAL_EPISODES: 32

name: ${TASK_NAME}/heldout_xp_eval

# heldout set
heldout_set:
  lbf:
    ippo_mlp: 
      path: "eval_teammates/lbf/ippo/2025-04-21_23-41-17/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]] # TODO: inspect each seed!
    # brdiv: 
    #   path: "eval_teammates/lbf/brdiv/2025-04-16/11-32-07/saved_train_run"
    #   actor_type: actor_with_conditional_critic
    #   idx_list: [[0, -1], [1, -1], [2, -1]] # If null, all checkpoints will be loaded.
    #   ckpt_key: checkpoints_conf # key to load from checkpoint. default is "checkpoints"
    #   POP_SIZE: 5 # for brdiv, we need to specify population size that the method was trained with
    ppo_ego_s5: 
      path: "results/lbf/ppo_ego_s5/2025-04-13_11-43-33/saved_train_run"
      actor_type: s5
      idx_list: [[0, -1]]
    # random_agent: 
    #   actor_type: random_agent
  overcooked-v1/cramped_room:
    ippo_mlp: 
      path: "eval_teammates/overcooked-v1/cramped_room/ippo/2025-04-21_22-53-04/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]]
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent
  overcooked-v1/asymm_advantages:
    ippo_mlp: 
      path: "eval_teammates/overcooked-v1/asymm_advantages/ippo/2025-04-21_22-53-56/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]]
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent
  overcooked-v1/counter_circuit:
    ippo_mlp: 
      path: "eval_teammates/overcooked-v1/counter_circuit/ippo/2025-04-21_22-55-42/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]]
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent
  overcooked-v1/forced_coord:
    ippo_mlp: 
      path: "eval_teammates/overcooked-v1/forced_coord/ippo/2025-04-21_23-00-17/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]]
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent
  overcooked-v1/coord_ring:
    ippo_mlp: 
      path: "eval_teammates/overcooked-v1/coord_ring/ippo/2025-04-21_22-58-26/saved_train_run"
      actor_type: mlp
      idx_list: [[0, -1], [1, -1]]
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent