defaults:
  - hydra: hydra_simple
  - _self_

ENV_NAME: lbf
ENV_KWARGS: {}
EVAL_SEED: 34957

name: heldout_eval

ego_agent:
  path: results/lbf/fcp_s5/2025-04-13_18-42-46/saved_train_run
  actor_type: s5
  idx: [0, -1] # seed and checkpoint index to evaluate
  # provide any necessary args to initialize the agent here
  # ex) S5_ACTOR_CRITIC_HIDDEN_DIM: 64
  # defaults for each actor type will be used if no args are provided

# heldout set
heldout_set:
  lbf: # doesn't matter what you name each agent
    brdiv: 
      path: "eval_teammates/lbf/brdiv/2025-04-16/11-32-07/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[2, 2], [3, 3]]
      ckpt_key: checkpoints_conf # key to load from checkpoint. default is "checkpoints"
      POP_SIZE: 5 # for brdiv, we need to specify population size that the method was trained with
    ppo_ego_s5: 
      path: "results/lbf/ppo_ego_s5/2025-04-13_11-43-33/saved_train_run"
      actor_type: s5
      idx_list: [[2, -1], [0, -1]]
    random_agent: 
      actor_type: random_agent
  
