# @package _global_
# THIS SCRIPT CONTAINS THE PATHS FOR THE HELDOUT EVALUATION. MODIFY WITH CAUTION.
global_heldout_settings:
  EVAL_SEED: 34957
  MAX_EPISODE_STEPS: ${task.ROLLOUT_LENGTH}
  NUM_EVAL_EPISODES: 64
  AGGREGATE_STAT: mean # choices: mean, iqm. both are computed with the bootstrapped CI using rliable.
  NORMALIZE_RETURNS: true # if true, use performance bounds to normalize returns

heldout_set:
  lbf:
    lbrdiv-conf: 
      path: "val_teammates/lbf/lbrdiv/2026-03-02_13-01-20/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]] # Select all agents in population for seed 0.
      ckpt_key: final_params_conf # key to load from checkpoint.
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        percent_eaten: [[0.0, 90.10], [0.0, 89.98], [0.0, 92.19]]
        returned_episode_returns: [[0.0, 0.45], [0.0, 0.45], [0.0, 0.46]]
    comedi: 
      path: "val_teammates/lbf/comedi/2026-03-02_00-58-19/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf # key to load from checkpoint.
      POP_SIZE: 10 # for comedi, we need to specify population size that the method was trained with
      test_mode: false
      performance_bounds:
        percent_eaten: [[0.0, 100.00], [0.0, 51.56], [0.0, 100.00], [0.0, 100.00], [0.0, 99.48]]
        returned_episode_returns: [[0.0, 0.50], [0.0, 0.32], [0.0, 0.50], [0.0, 0.50], [0.0, 0.50]]
  overcooked-v1/cramped_room:
    lbrdiv-conf: 
      path: "val_teammates/overcooked-v1/cramped_room/lbrdiv/2026-03-03_19-04-46/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_conf
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
    comedi: 
      path: "val_teammates/overcooked-v1/cramped_room/comedi/2026-03-03_22-28-24/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
  overcooked-v1/asymm_advantages:
    lbrdiv-conf: 
      path: "val_teammates/overcooked-v1/asymm_advantages/lbrdiv/2026-03-03_17-02-53/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_conf
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
    comedi: 
      path: "val_teammates/overcooked-v1/asymm_advantages/comedi/2026-03-03_17-06-25/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
  overcooked-v1/counter_circuit:
    lbrdiv-conf: 
      path: "val_teammates/overcooked-v1/counter_circuit/lbrdiv/2026-03-03_17-49-14/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_conf
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
    comedi: 
      path: "val_teammates/overcooked-v1/counter_circuit/comedi/2026-03-03_19-57-43/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
  overcooked-v1/coord_ring:
    lbrdiv-conf: 
      path: "val_teammates/overcooked-v1/coord_ring/lbrdiv/2026-03-02_14-56-18/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_conf
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
    comedi: 
      path: "val_teammates/overcooked-v1/coord_ring/comedi/2026-03-01_22-32-32/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
  overcooked-v1/forced_coord:
    lbrdiv-conf: 
      path: "val_teammates/overcooked-v1/forced_coord/lbrdiv/2026-03-03_19-30-49/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_conf
      POP_SIZE: 3
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
    comedi: 
      path: "val_teammates/overcooked-v1/forced_coord/comedi/2026-03-04_00-28-31/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
      performance_bounds:
        base_return: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
        returned_episode_returns: [[0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0], [0.0, 100.0]]
  
best_response_set:
  lbf:
    lbrdiv-br: # Use BR policies generated by LBRDiv
      path: "val_teammates/lbf/lbrdiv/2026-03-02_13-01-20/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]] # Select all agents in population for seed 0.
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br: # Use same policy as best response as CoMeDi maximizes SP
      path: "val_teammates/lbf/comedi/2026-03-02_00-58-19/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
  overcooked-v1/cramped_room:
    lbrdiv-br:
      path: "val_teammates/overcooked-v1/cramped_room/lbrdiv/2026-03-03_19-04-46/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br:
      path: "val_teammates/overcooked-v1/cramped_room/comedi/2026-03-03_22-28-24/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
  overcooked-v1/asymm_advantages:
    lbrdiv-br:
      path: "val_teammates/overcooked-v1/asymm_advantages/lbrdiv/2026-03-03_17-02-53/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br:
      path: "val_teammates/overcooked-v1/asymm_advantages/comedi/2026-03-03_17-06-25/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
  overcooked-v1/counter_circuit:
    lbrdiv-br:
      path: "val_teammates/overcooked-v1/counter_circuit/lbrdiv/2026-03-03_17-49-14/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br:
      path: "val_teammates/overcooked-v1/counter_circuit/comedi/2026-03-03_19-57-43/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
  overcooked-v1/coord_ring:
    lbrdiv-br:
      path: "val_teammates/overcooked-v1/coord_ring/lbrdiv/2026-03-02_14-56-18/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br:
      path: "val_teammates/overcooked-v1/coord_ring/comedi/2026-03-01_22-32-32/saved_train_run/"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
  overcooked-v1/forced_coord:
    lbrdiv-br:
      path: "val_teammates/overcooked-v1/forced_coord/lbrdiv/2026-03-03_19-30-49/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2]]
      ckpt_key: final_params_br
      POP_SIZE: 3
      test_mode: false
    comedi-br:
      path: "val_teammates/overcooked-v1/forced_coord/comedi/2026-03-04_00-28-31/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4]]
      ckpt_key: final_params_conf
      POP_SIZE: 10
      test_mode: false
