TOTAL_TIMESTEPS: 1e6 
LR: .0001
NUM_ENVS: 16
NUM_STEPS: 128 # rollout length
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
NUM_CHECKPOINTS: 5
NUM_SEEDS: 3
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.05
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: True
