defaults:
  - ppo_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1.2e8
NUM_MINIBATCHES: 8
LR: 3e-5
ENT_COEF: .001
CLIP_EPS: 0.1
UPDATE_EPOCHS: 10
ANNEAL_LR: false