defaults:
  - ppo_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1.2e8
NUM_MINIBATCHES: 8
LR: 1e-5
ENT_COEF: 1e-4
CLIP_EPS: 0.1
UPDATE_EPOCHS: 5
ANNEAL_LR: false
