defaults:
  - liam_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 6e7
UPDATE_EPOCHS: 10
CLIP_EPS: 0.04
ENCODER_DECODER_LR: 1e-5
ENT_COEF: 0.01
LR: 3e-3
NUM_ENVS: 80
