defaults:
  - ippo_defaults@PARTNER_TRAIN_ARGS   # import values from ippo_defaults.yaml to PARTNER_TRAIN_ARGS
  - ippo_defaults@FCP_TRAIN_ARGS  # import values from ippo_defaults.yaml to FCP_TRAIN_ARGS
  - ippo_defaults@FCP_EVAL_ARGS  # import values from ippo_defaults.yaml to FCP_TRAIN_ARGS
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: lbf
ENV_KWARGS: {}

PARTNER_TRAIN_ARGS: 
  TOTAL_TIMESTEPS: 1e6 # specify arg to override default value
  ENV_NAME: ${ENV_NAME}
  TRAIN_PATH: null # results/lbf/2025-02-13_21-21-35/train_run.pkl # set to null to train from scratch
  TRAIN_SEED: 1285842
  EVAL_PATH: null # results/lbf/2025-02-13_21-42-20/train_run.pkl # set to null to train from scratch
  EVAL_SEED: 112358

FCP_TRAIN_ARGS: 
  ENV_NAME: ${ENV_NAME}
  SEED: 38410

FCP_EVAL_ARGS: 
  ENV_NAME: ${ENV_NAME}
  SEED: 12345

# WandB Params
ENTITY: 
PROJECT: continual-aht
WANDB_MODE : disabled

# Hydra params
hydra:
  job:
    name: fcp_ippo
  run:
    dir: results/${ENV_NAME}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
