defaults:
  - drqnppo/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 3e6
EPSILON_END: 0.05
EPSILON_EXPLORATION_FRACTION: 0.5

TARGET_UPDATE_INTERVAL: 1
TAU: 0.005
LEARNING_STARTS: 1000