defaults:
  - open_ended_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 3e6
TIMESTEPS_PER_ITER_EGO: 1e6
NUM_OPEN_ENDED_ITERS: 30
LOWER_REGRET_THRESHOLD_START: 0.0 # min regret is 0.0 - 150 = -250
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 60.0 # max regret is 250 - 0 = 250
UPPER_REGRET_THRESHOLD_END: 60.0
# LOWER_REGRET_THRESHOLD_START: -250 # 0.0 # min regret is 0.0 - 150 = -250
# LOWER_REGRET_THRESHOLD_END: 0.0 # 0.0
# UPPER_REGRET_THRESHOLD_START: 250 # 60.0 # max regret is 250 - 0 = 250
# UPPER_REGRET_THRESHOLD_END: 60 # 60.0
LAGRANGE_MULTIPLIER_LR: 0.001
LR: .0001
NUM_MINIBATCHES: 8
CLIP_EPS: 0.2
ENT_COEF: 0.01