defaults:
  - meliba_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 3e7
NUM_ENVS: 256
UPDATE_EPOCHS: 5
CLIP_EPS: 0.5
DECODER_KL_WEIGHT: 0.01
ENCODER_DECODER_LR: 1e-3
ENT_COEF: 1e-4
LR: 3e-4
