defaults:
  - oe_persistent/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 6e6
TIMESTEPS_PER_ITER_EGO: 2e6
NUM_OPEN_ENDED_ITERS: 30
REGRET_SP_WEIGHT: 2.0 # weight on the SP term in the perstep regret loss
LOWER_REGRET_THRESHOLD_START: 0.0
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 60.0
UPPER_REGRET_THRESHOLD_END: 60.0
LAGRANGE_MULTIPLIER_LR: 0.01
LR: .0001
NUM_MINIBATCHES: 8
CLIP_EPS: 0.3
ENT_COEF: 0.01
PRETRAIN_ARGS:
  TOTAL_TIMESTEPS: 1e6 # timesteps to split between IPPO partners
  NUM_AGENTS: 3 # number of IPPO partners to pretrain
  NUM_CHECKPOINTS: 2 # number of checkpoints to save for each IPPO partner

