defaults:
  - ippo/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 6e7
NUM_ENVS: 1000
NUM_MINIBATCHES: 125
LR: 0.001
ENT_COEF: 0.05
CLIP_EPS: 0.3
ANNEAL_LR: false
UPDATE_EPOCHS: 4
S5_D_MODEL: 128
S5_SSM_SIZE: 128
S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
FC_N_LAYERS: 3
ACTIVATION: "relu"