defaults:
  - oe_persistent_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1.5e6
TIMESTEPS_PER_ITER_EGO: 1e6
NUM_OPEN_ENDED_ITERS: 30
LOWER_REGRET_THRESHOLD_START: 0.0
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 40.0
UPPER_REGRET_THRESHOLD_END: 40.0
LAGRANGE_MULTIPLIER_LR: 0.05
LR: .0001
NUM_MINIBATCHES: 8
CLIP_EPS: 0.3
ENT_COEF: 0.01
