defaults:
  - oe_persistent_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 4.5e6 # per iter of open-ended training, divided between conf-br and conf-ego and between all partner seeds
TIMESTEPS_PER_ITER_EGO: 3e6
NUM_OPEN_ENDED_ITERS: 20
<<<<<<< HEAD:open_ended_training/configs/algorithm/oe_persistent_lagrange/overcooked/forced_coord.yaml
LOWER_REGRET_THRESHOLD_START: 0.0
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 40.0
UPPER_REGRET_THRESHOLD_END: 40.0
LAGRANGE_MULTIPLIER_LR: 0.05
=======
LOWER_REGRET_THRESHOLD: 0.0
UPPER_REGRET_THRESHOLD: 60.0
LAGRANGE_MULTIPLIER_LR: 0.001
>>>>>>> main:open_ended_training/configs/algorithm/oe_persistent_paired/overcooked/forced_coord.yaml
LR: 1e-3
NUM_MINIBATCHES: 8
CLIP_EPS: 0.1
ENT_COEF: 0.05