ENV_NAME: rddl/grid_10x10_alternating
ROLLOUT_LENGTH: 128
NUM_EVAL_EPISODES: 10
ENV_KWARGS: {domain: "toroidal/yielding/grid_10x10_alternating_domain.rddl",
             instance: "toroidal/grid_10x10_alternating_instance2.rddl",
             render: true,
             render_name: "grid_10x10_alternating_toroidal_full_restrictions",
             render_dir: "render",
             stochastic_movement_prob: 0.1,
             enforce_action_constraints: true,
             vectorized: true,
             ego_centric_obs: true}
NO_LAW_ENV_KWARGS: {domain: "toroidal/no_restrictions/grid_10x10_alternating_domain.rddl",
                    instance: "toroidal/grid_10x10_alternating_instance2.rddl",
                    render: true,
                    render_name: "grid_10x10_alternating_toroidal_no_restrictions",
                    render_dir: "render",
                    stochastic_movement_prob: 0.1,
                    enforce_action_constraints: true,
                    vectorized: true,
                    ego_centric_obs: true}
TASK_NAME: rddl/grid_10x10_alternating/toroidal_full_restrictions
SINGLE_AGENT_1_PROJECTION: "toroidal/grid_10x10_alternating_instance0.rddl"
SINGLE_AGENT_2_PROJECTION: "toroidal/grid_10x10_alternating_instance1.rddl"
ALPHA_COST: true