defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS_PER_ITERATION: 1e6
PARTNER_POP_SIZE: 3
NUM_ENVS_SP: 32
NUM_ENVS_XP: 32
NUM_ENVS_MP: 32
XP_LOSS_WEIGHTS: 0.1
LR: 5e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
CLIP_EPS: 0.05
ENT_COEF: 0.01
