defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS_PER_ITERATION: 1e7
PARTNER_POP_SIZE: 30
LR: 5e-4
UPDATE_EPOCHS: 15
CLIP_EPS: 0.05
ENT_COEF: 0.001
COMEDI_ALPHA: 0.2
COMEDI_BETA: 0.4
