# @package value_function
# ^ tells hydra to place these value directly under algorithm key
ALG: drqnppo
NETWORK_TYPE: s5
NUM_TRAIN_SEEDS: 1
TOTAL_TIMESTEPS: 3e6
NUM_CHECKPOINTS: 5
NUM_ENVS: 8
LR: 2.5e-4
TARGET_UPDATE_INTERVAL: 500
BUFFER_SIZE: 10000
BUFFER_BATCH_SIZE: 128
GAMMA: 0.99
TAU: 1.0
EPSILON_START: 1.0
EPSILON_END: 0.1
EPSILON_EXPLORATION_FRACTION: 0.5
LEARNING_STARTS: 10000
TRAINING_INTERVAL: 10
MAX_GRAD_NORM: 1.0
ANNEAL_LR: false

TRAIN_EVAL: true

RNN_HIDDEN_DIM: 64

S5_D_MODEL: 128
S5_SSM_SIZE: 128
S5_N_LAYERS: 1