defaults:
  - oe_persistent_paired/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1.5e6 # per iter of open-ended training, divided between conf-br and conf-ego and between all partner seeds
TIMESTEPS_PER_ITER_EGO: 1e6
NUM_OPEN_ENDED_ITERS: 30
LOWER_REGRET_THRESHOLD: 0.
UPPER_REGRET_THRESHOLD: 0.2
LAGRANGE_MULTIPLIER_LR: 0.001
LR: 1e-3
CLIP_EPS: 0.1
ENT_COEF: 0.05