defaults:
  - task: overcooked/coord_ring # task configs
  - algorithm@algorithm: oe_paired_resets/${task} # task-specific algorithm configs
  - hydra: hydra_simple
  - ../../evaluation/configs/global_heldout_settings
  - _self_

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
ROLLOUT_LENGTH: ${task.ROLLOUT_LENGTH}
TASK_NAME: ${task.TASK_NAME}

# whether to run a heldout evaluation of the ego agent
run_heldout_eval: true

# teammate generation settings
algorithm:
  NUM_EVAL_EPISODES: 20 # used during training
  NUM_SEEDS: 1
  TRAIN_SEED: 20374
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}
  # Debug flag
  # NUM_OPEN_ENDED_ITERS: 2
  # TIMESTEPS_PER_ITER_PARTNER: 1e7 # per iter of open-ended training, divided between 4 types of rollouts and all partner seeds
  # TIMESTEPS_PER_ITER_EGO: 1e6 # 2e6
  # ANNEAL_LR: false
  # EGO_ARGS:
  #   LR: 5e-5
  #   ENT_COEF: .001
  #   CLIP_EPS: 0.1
  #   ANNEAL_LR: false
  #   UPDATE_EPOCHS: 10

label: ""
name: ${TASK_NAME}/${algorithm.ALG}/${label}

# wandb settings
logger: 
  project: open-ended-aht
  entity: aht-project
  tags: 
    - ${algorithm.ALG}
    - ${TASK_NAME}
    - seed=${algorithm.TRAIN_SEED}
    - ${label}
  mode: online # options: online, offline, disabled
  verbose: false
  log_train_out: true # whether to log the out dictionary
  log_eval_out: true # whether to log the eval metrics

# Local logger
local_logger:
  save_figures: false # unused
  save_train_out: true
  save_eval_out: true
