defaults:
  - hydra: hydra_simple
  - heldout_eval
  - _self_

ENV_NAME: lbf
ROLLOUT_LENGTH: 128
ENV_KWARGS: {}
TASK_NAME: lbf

algorithm:
  ALG: fcp
  NUM_OPEN_ENDED_ITERS: 10
  PARTNER_POP_SIZE: 3 # Since FCP is trained against all checkpoints of partners, true pop size is PARTNER_POP_SIZE * NUM_CHECKPOINTS
  NUM_EVAL_EPISODES: 20
  TRAIN_SEED: 38410
  NUM_ENVS: 16
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}
  TOTAL_TIMESTEPS: 3e4 # 3e5  # per iter of open-ended training
  LR: 1.e-4
  UPDATE_EPOCHS: 15
  NUM_MINIBATCHES: 4
  NUM_CHECKPOINTS: 5
  GAMMA: 0.99
  GAE_LAMBDA: 0.95
  CLIP_EPS: 0.05
  ENT_COEF: 0.01
  VF_COEF: 1.0
  MAX_GRAD_NORM: 1.0
  ANNEAL_LR: false

name: open_ended_fcp

# wandb settings
logger: 
  load_dir: open_ended_fcp
  project: open-ended-aht
  entity: aht-project
  mode: online # options: online, offline, disabled
  verbose: true
  log_train_out: false # whether to log the out dictionary
  log_eval_out: false # whether to log the heldout eval metrics

# Local logger
local_logger:
  save_figures: true # currently unused
  save_train_out: true
  save_eval_out: true