defaults:
  - hydra: hydra_simple
  - _self_

ENV_NAME: lbf
ROLLOUT_LENGTH: 128
ENV_KWARGS: {}

algorithm:
  ALG: minimax
  NUM_OPEN_ENDED_ITERS: 20
  NUM_ENVS: 16
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH} 
  TOTAL_TIMESTEPS: 1e6 
  LR: 1.e-4
  UPDATE_EPOCHS: 15
  MAX_EVAL_EPISODES: 20
  NUM_MINIBATCHES: 16
  NUM_CHECKPOINTS: 5
  GAMMA: 0.99
  GAE_LAMBDA: 0.95
  CLIP_EPS: 0.05
  ENT_COEF: 0.01
  VF_COEF: 1.0
  MAX_GRAD_NORM: 1.0
  ACTIVATION: tanh
  ANNEAL_LR: true
  TRAIN_PARTNER_SEED: 112358
  EVAL_PARTNER_SEED: 1285842
  TRAIN_SEED: 38410
  EVAL_SEED: 12345
  NUM_SEEDS: 3
  S5_ACTOR_CRITIC_HIDDEN_DIM: 64
  S5_D_MODEL: 16
  S5_SSM_SIZE: 16
  S5_N_LAYERS: 2
  S5_BLOCKS: 1
  S5_ACTIVATION: full_glu
  S5_DO_NORM: true
  S5_PRENORM: true
  S5_DO_GTRXL_NORM: true

name: open_ended_minimax

# wandb settings
logger:
  load_dir: open_ended_minimax
  project: open-ended-aht
  entity: aht-project
  mode: online # options: online, offline, disabled
  verbose: true
