# @package algorithm
# ^ tells hydra to place these value directly under algorithm key

ALG: open_ended_paired
TOTAL_TIMESTEPS: 1e6  # per iter of open-ended training
NUM_CHECKPOINTS: 1 # per iter of open-ended training
NUM_OPEN_ENDED_ITERS: 30
PARTNER_POP_SIZE: 5
CONF_BR_WEIGHT: 0.5 # conf-ego weight set to 1 - conf-br weight
NUM_ENVS: 16
LR: 1.e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.05
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: false
