ENV_NAME: continuous/coop_recon_sap
TASK_NAME: CoopRecon_Compare_No_law_5AgentProjection
ROLLOUT_LENGTH: 128
NUM_EVAL_EPISODES: 50

ENV_KWARGS:
  num_agents: 5
  grid_size: 1.5
  ego_centric_obs: true
  movement_noise_std: 0.1
  done_condition: "all"
  horizon: 150
  render: false
  render_name: "cooprecon_compare_no_law_5agentprojection"
  social_min_dist: 0.0
  min_sep_goal: 0.0
  collision_radius: 0.05

ALPHA_COST: false
