ENV_NAME: continuous/coop_recon
ROLLOUT_LENGTH: 128
NUM_EVAL_EPISODES: 10
ENV_KWARGS:
  {
    instance: "",
    render: true,
    render_name: "coop_recon_continuous",
    render_dir: "render",
    ego_centric_obs: false,
    movement_noise_std: 0.1,  # 10% of max step size; actual std = 0.1 * dt(0.05) = 0.005 units
  }
TASK_NAME: continuous/coop_recon
SINGLE_AGENT_1_PROJECTION: ""
SINGLE_AGENT_2_PROJECTION: ""
