defaults:
  - task: # rddl/grid_4x4 # task configs
  - algorithm@algorithm: # ppo/${task} # task-specific algorithm configs
  - hydra: hydra_simple
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
ROLLOUT_LENGTH: ${task.ROLLOUT_LENGTH}
TASK_NAME: ${task.TASK_NAME}
NUM_EVAL_EPISODES: ${task.NUM_EVAL_EPISODES}

NUM_EXPT_AGENTS: 2

# partner configs are specified in each algorithm _base_ config file
# note that ppo_ego and ppo_br support different types of partner configs
algorithm:
  USE_SAME_SEED: false
  TRAIN_SEED:
  EVAL_SEED:
  FIXED_EVAL: false
  NUM_EVAL_EPISODES: ${NUM_EVAL_EPISODES}
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}

label: "default_label"
social_law_label: null # if not null, this will be added as a tag in WandB and appended to the name.
name: ${TASK_NAME}/${algorithm.ALG}_${algorithm.ACTOR_TYPE}/${label}

# WandB Params
logger:
  project: stochastic-policies-jax
  entity: social-laws-project
  tags:
    - ${algorithm.ALG}
    - ${TASK_NAME}
    - ${label}
    - ${NUM_EXPT_AGENTS} agents
    - ${social_law_label} # Must be last tag in the list since it may be popped if null.
  mode: online # options: online, offline, disabled
  verbose: false
  log_train_out: false # whether to log the out dictionary
  log_eval_out: true # whether to log the eval metrics

# Local logger
local_logger:
  save_train_out: false
  save_eval_out: true
