#!/usr/bin/env python3
"""
Script to analyze profile results generated by app.py.

Usage:
    python analyze_profile.py                          # Serve interactive viewer on localhost:9999
    python analyze_profile.py --port 8080              # Serve on custom port
    python analyze_profile.py --console                # Print to console (old behavior)
    python analyze_profile.py --console --all          # Analyze all profiles in console
"""

import os
import sys
import glob
import pstats
import io
import json
from pathlib import Path
from flask import Flask, render_template_string, jsonify, request
from datetime import datetime
import webbrowser
import threading
import time


# HTML template for the profile viewer
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Profile Viewer</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 8px 8px 0 0;
        }
        
        .header h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }
        
        .header p {
            opacity: 0.9;
            font-size: 14px;
        }
        
        .controls {
            padding: 20px 30px;
            background: #f8f9fa;
            border-bottom: 1px solid #e0e0e0;
        }
        
        .controls select, .controls input {
            padding: 8px 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            margin-right: 10px;
        }
        
        .controls button {
            padding: 8px 16px;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            margin-right: 10px;
        }
        
        .controls button:hover {
            background: #5568d3;
        }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 20px 30px;
            border-bottom: 1px solid #e0e0e0;
        }
        
        .stat-card {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            border-left: 4px solid #667eea;
        }
        
        .stat-card .label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 5px;
        }
        
        .stat-card .value {
            font-size: 24px;
            font-weight: 600;
            color: #333;
        }
        
        .tabs {
            display: flex;
            padding: 0 30px;
            background: #f8f9fa;
            border-bottom: 2px solid #e0e0e0;
        }
        
        .tab {
            padding: 15px 25px;
            cursor: pointer;
            border-bottom: 3px solid transparent;
            margin-bottom: -2px;
            font-weight: 500;
            color: #666;
            transition: all 0.2s;
        }
        
        .tab:hover {
            color: #667eea;
        }
        
        .tab.active {
            color: #667eea;
            border-bottom-color: #667eea;
        }
        
        .tab-content {
            display: none;
            padding: 20px 30px;
        }
        
        .tab-content.active {
            display: block;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }
        
        th {
            background: #f8f9fa;
            padding: 12px 8px;
            text-align: left;
            font-weight: 600;
            color: #333;
            border-bottom: 2px solid #e0e0e0;
            position: sticky;
            top: 0;
            cursor: pointer;
            user-select: none;
            transition: background 0.2s;
        }
        
        th:hover {
            background: #e9ecef;
        }
        
        th.sortable::after {
            content: ' ⇅';
            opacity: 0.3;
            font-size: 10px;
        }
        
        th.sort-asc::after {
            content: ' ▲';
            opacity: 1;
            color: #667eea;
        }
        
        th.sort-desc::after {
            content: ' ▼';
            opacity: 1;
            color: #667eea;
        }
        
        td {
            padding: 10px 8px;
            border-bottom: 1px solid #f0f0f0;
        }
        
        tr:hover {
            background: #f8f9fa;
        }
        
        .number {
            font-family: 'Courier New', monospace;
            text-align: right;
        }
        
        .filename {
            color: #0066cc;
            font-family: 'Courier New', monospace;
            font-size: 12px;
        }
        
        .bar-container {
            background: #e0e0e0;
            border-radius: 3px;
            height: 20px;
            position: relative;
            overflow: hidden;
        }
        
        .bar {
            background: linear-gradient(90deg, #667eea, #764ba2);
            height: 100%;
            border-radius: 3px;
            display: flex;
            align-items: center;
            padding: 0 8px;
            color: white;
            font-size: 11px;
            font-weight: 600;
        }
        
        .filter-box {
            margin: 10px 0;
            padding: 10px;
            background: #fff;
            border: 1px solid #e0e0e0;
            border-radius: 4px;
        }
        
        .filter-box input {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        
        .loading {
            text-align: center;
            padding: 40px;
            color: #666;
        }
        
        .spinner {
            border: 3px solid #f3f3f3;
            border-top: 3px solid #667eea;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            animation: spin 1s linear infinite;
            margin: 0 auto 20px;
        }
        
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        
        .flamegraph-placeholder {
            padding: 40px;
            text-align: center;
            background: #f8f9fa;
            border: 2px dashed #ccc;
            border-radius: 8px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔥 Python Profile Viewer</h1>
            <p>Interactive profiling analysis for step() function</p>
        </div>
        
        <div class="controls">
            <select id="profileSelect" onchange="loadProfile()">
                <option value="">Select a profile...</option>
            </select>
            <input type="number" id="topN" value="50" min="10" max="500" step="10" placeholder="Show top N">
            <button onclick="loadProfile()">Refresh</button>
            <button onclick="downloadProfile()">Download .prof</button>
        </div>
        
        <div id="statsGrid" class="stats-grid" style="display: none;">
            <div class="stat-card">
                <div class="label">Total Time</div>
                <div class="value" id="totalTime">-</div>
            </div>
            <div class="stat-card">
                <div class="label">Function Calls</div>
                <div class="value" id="totalCalls">-</div>
            </div>
            <div class="stat-card">
                <div class="label">Primitive Calls</div>
                <div class="value" id="primitiveCalls">-</div>
            </div>
            <div class="stat-card">
                <div class="label">Profile File</div>
                <div class="value" id="fileName" style="font-size: 14px;">-</div>
            </div>
        </div>
        
        <div class="tabs">
            <div class="tab active" onclick="switchTab('cumulative')">Cumulative Time</div>
            <div class="tab" onclick="switchTab('tottime')">Total Time</div>
            <div class="tab" onclick="switchTab('calls')">Call Count</div>
            <div class="tab" onclick="switchTab('callers')">Callers/Callees</div>
        </div>
        
        <div id="cumulative" class="tab-content active">
            <div class="filter-box">
                <input type="text" id="filterCumulative" onkeyup="filterTable('tableCumulative', 'filterCumulative')" 
                       placeholder="Filter by function name...">
            </div>
            <div style="overflow-x: auto;">
                <table id="tableCumulative">
                    <thead>
                        <tr>
                            <th class="sortable" onclick="sortTable('tableCumulative', 0, 'string')">Function</th>
                            <th class="sortable number" onclick="sortTable('tableCumulative', 1, 'number')">Calls</th>
                            <th class="sortable number" onclick="sortTable('tableCumulative', 2, 'number')">Total Time (s)</th>
                            <th class="sortable number" onclick="sortTable('tableCumulative', 3, 'number')">Per Call (ms)</th>
                            <th class="sortable number" onclick="sortTable('tableCumulative', 4, 'number')">Cumulative (s)</th>
                            <th class="sortable number" onclick="sortTable('tableCumulative', 5, 'number')">Per Call (ms)</th>
                            <th class="sortable" onclick="sortTable('tableCumulative', 6, 'number')">% Time</th>
                        </tr>
                    </thead>
                    <tbody id="bodyTableCumulative">
                        <tr><td colspan="7" class="loading"><div class="spinner"></div>Select a profile to view data</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div id="tottime" class="tab-content">
            <div class="filter-box">
                <input type="text" id="filterTottime" onkeyup="filterTable('tableTottime', 'filterTottime')" 
                       placeholder="Filter by function name...">
            </div>
            <div style="overflow-x: auto;">
                <table id="tableTottime">
                    <thead>
                        <tr>
                            <th class="sortable" onclick="sortTable('tableTottime', 0, 'string')">Function</th>
                            <th class="sortable number" onclick="sortTable('tableTottime', 1, 'number')">Calls</th>
                            <th class="sortable number" onclick="sortTable('tableTottime', 2, 'number')">Total Time (s)</th>
                            <th class="sortable number" onclick="sortTable('tableTottime', 3, 'number')">Per Call (ms)</th>
                            <th class="sortable number" onclick="sortTable('tableTottime', 4, 'number')">Cumulative (s)</th>
                            <th class="sortable" onclick="sortTable('tableTottime', 5, 'number')">% Time</th>
                        </tr>
                    </thead>
                    <tbody id="bodyTableTottime">
                        <tr><td colspan="6" class="loading">Select a profile to view data</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div id="calls" class="tab-content">
            <div class="filter-box">
                <input type="text" id="filterCalls" onkeyup="filterTable('tableCalls', 'filterCalls')" 
                       placeholder="Filter by function name...">
            </div>
            <div style="overflow-x: auto;">
                <table id="tableCalls">
                    <thead>
                        <tr>
                            <th class="sortable" onclick="sortTable('tableCalls', 0, 'string')">Function</th>
                            <th class="sortable number" onclick="sortTable('tableCalls', 1, 'number')">Call Count</th>
                            <th class="sortable number" onclick="sortTable('tableCalls', 2, 'number')">Cumulative (s)</th>
                            <th class="sortable" onclick="sortTable('tableCalls', 3, 'number')">Calls Per Second</th>
                        </tr>
                    </thead>
                    <tbody id="bodyTableCalls">
                        <tr><td colspan="4" class="loading">Select a profile to view data</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div id="callers" class="tab-content">
            <div class="flamegraph-placeholder">
                <h3>Caller/Callee Analysis</h3>
                <p>Select a function from the other tabs to view its callers and callees</p>
                <p style="margin-top: 20px; font-size: 12px; color: #999;">
                    Tip: Click on any function name in the tables to see what calls it and what it calls
                </p>
            </div>
        </div>
    </div>
    
    <script>
        let currentProfile = null;
        let profileData = null;
        let sortState = {}; // Track sort direction for each table
        
        // Load available profiles on page load
        window.onload = function() {
            fetch('/api/profiles')
                .then(r => r.json())
                .then(data => {
                    const select = document.getElementById('profileSelect');
                    data.profiles.forEach(p => {
                        const option = document.createElement('option');
                        option.value = p.filename;
                        option.textContent = `${p.filename} (${p.size})`;
                        select.appendChild(option);
                    });
                    
                    // Auto-load most recent if available
                    if (data.profiles.length > 0) {
                        select.value = data.profiles[0].filename;
                        loadProfile();
                    }
                });
        };
        
        function loadProfile() {
            const filename = document.getElementById('profileSelect').value;
            const topN = document.getElementById('topN').value || 50;
            
            if (!filename) return;
            
            currentProfile = filename;
            
            // Show loading state
            document.getElementById('statsGrid').style.display = 'none';
            
            fetch(`/api/analyze?filename=${encodeURIComponent(filename)}&top_n=${topN}`)
                .then(r => r.json())
                .then(data => {
                    profileData = data;
                    displayProfile(data);
                })
                .catch(err => {
                    console.error('Error loading profile:', err);
                    alert('Error loading profile: ' + err.message);
                });
        }
        
        function displayProfile(data) {
            // Update stats
            document.getElementById('statsGrid').style.display = 'grid';
            document.getElementById('totalTime').textContent = data.stats.total_time.toFixed(4) + 's';
            document.getElementById('totalCalls').textContent = data.stats.total_calls.toLocaleString();
            document.getElementById('primitiveCalls').textContent = data.stats.primitive_calls.toLocaleString();
            document.getElementById('fileName').textContent = data.filename;
            
            // Update tables
            updateTable('tableCumulative', data.cumulative, data.stats.total_tt);
            updateTable('tableTottime', data.tottime, data.stats.total_tt);
            updateTable('tableCalls', data.calls, data.stats.total_tt);
        }
        
        function updateTable(tableId, stats, totalTime) {
            const tbody = document.getElementById('body' + tableId.charAt(0).toUpperCase() + tableId.slice(1));
            tbody.innerHTML = '';
            
            stats.forEach(stat => {
                const row = tbody.insertRow();
                
                const funcCell = row.insertCell();
                funcCell.innerHTML = `<div class="filename">${escapeHtml(stat.function)}</div>`;
                
                const callsCell = row.insertCell();
                callsCell.className = 'number';
                callsCell.textContent = stat.ncalls.toLocaleString();
                
                if (tableId === 'tableCumulative') {
                    const tottimeCell = row.insertCell();
                    tottimeCell.className = 'number';
                    tottimeCell.textContent = stat.tottime.toFixed(4);
                    
                    const percall1Cell = row.insertCell();
                    percall1Cell.className = 'number';
                    percall1Cell.textContent = (stat.percall_tot * 1000).toFixed(3);
                    
                    const cumtimeCell = row.insertCell();
                    cumtimeCell.className = 'number';
                    cumtimeCell.textContent = stat.cumtime.toFixed(4);
                    
                    const percall2Cell = row.insertCell();
                    percall2Cell.className = 'number';
                    percall2Cell.textContent = (stat.percall_cum * 1000).toFixed(3);
                    
                    const pctCell = row.insertCell();
                    const pct = (stat.cumtime / totalTime * 100);
                    pctCell.innerHTML = `
                        <div class="bar-container">
                            <div class="bar" style="width: ${pct}%">${pct.toFixed(1)}%</div>
                        </div>
                    `;
                } else if (tableId === 'tableTottime') {
                    const tottimeCell = row.insertCell();
                    tottimeCell.className = 'number';
                    tottimeCell.textContent = stat.tottime.toFixed(4);
                    
                    const percallCell = row.insertCell();
                    percallCell.className = 'number';
                    percallCell.textContent = (stat.percall_tot * 1000).toFixed(3);
                    
                    const cumtimeCell = row.insertCell();
                    cumtimeCell.className = 'number';
                    cumtimeCell.textContent = stat.cumtime.toFixed(4);
                    
                    const pctCell = row.insertCell();
                    const pct = (stat.tottime / totalTime * 100);
                    pctCell.innerHTML = `
                        <div class="bar-container">
                            <div class="bar" style="width: ${pct}%">${pct.toFixed(1)}%</div>
                        </div>
                    `;
                } else if (tableId === 'tableCalls') {
                    const cumtimeCell = row.insertCell();
                    cumtimeCell.className = 'number';
                    cumtimeCell.textContent = stat.cumtime.toFixed(4);
                    
                    const cpsCell = row.insertCell();
                    const cps = stat.cumtime > 0 ? stat.ncalls / stat.cumtime : 0;
                    cpsCell.innerHTML = `
                        <div class="bar-container">
                            <div class="bar" style="width: ${Math.min(100, cps / 1000 * 100)}%">
                                ${cps.toFixed(0)} calls/s
                            </div>
                        </div>
                    `;
                }
            });
        }
        
        function switchTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            
            // Show selected tab
            document.getElementById(tabName).classList.add('active');
            event.target.classList.add('active');
        }
        
        function filterTable(tableId, filterId) {
            const filter = document.getElementById(filterId).value.toLowerCase();
            const tbody = document.getElementById('body' + tableId.charAt(0).toUpperCase() + tableId.slice(1));
            const rows = tbody.getElementsByTagName('tr');
            
            for (let i = 0; i < rows.length; i++) {
                const funcCell = rows[i].getElementsByTagName('td')[0];
                if (funcCell) {
                    const text = funcCell.textContent || funcCell.innerText;
                    rows[i].style.display = text.toLowerCase().indexOf(filter) > -1 ? '' : 'none';
                }
            }
        }
        
        function downloadProfile() {
            if (!currentProfile) {
                alert('No profile selected');
                return;
            }
            window.location.href = `/api/download?filename=${encodeURIComponent(currentProfile)}`;
        }
        
        function escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }
        
        function sortTable(tableId, columnIndex, dataType) {
            const table = document.getElementById(tableId);
            const tbody = table.querySelector('tbody');
            const rows = Array.from(tbody.querySelectorAll('tr'));
            
            // Initialize sort state for this table if needed
            if (!sortState[tableId]) {
                sortState[tableId] = { column: -1, ascending: true };
            }
            
            // Determine sort direction
            let ascending = true;
            if (sortState[tableId].column === columnIndex) {
                ascending = !sortState[tableId].ascending;
            }
            sortState[tableId] = { column: columnIndex, ascending: ascending };
            
            // Clear all sort indicators
            table.querySelectorAll('th').forEach(th => {
                th.classList.remove('sort-asc', 'sort-desc');
            });
            
            // Add sort indicator to current column
            const headerCells = table.querySelectorAll('th');
            if (ascending) {
                headerCells[columnIndex].classList.add('sort-asc');
            } else {
                headerCells[columnIndex].classList.add('sort-desc');
            }
            
            // Sort the rows
            rows.sort((a, b) => {
                const aCell = a.cells[columnIndex];
                const bCell = b.cells[columnIndex];
                
                let aVal, bVal;
                
                if (dataType === 'number') {
                    // For percentage columns, extract number from the bar div
                    if (columnIndex === 6 && tableId === 'tableCumulative') {
                        const aBar = aCell.querySelector('.bar');
                        const bBar = bCell.querySelector('.bar');
                        aVal = aBar ? parseFloat(aBar.textContent) : 0;
                        bVal = bBar ? parseFloat(bBar.textContent) : 0;
                    } else if ((columnIndex === 5 && tableId === 'tableTottime') || 
                               (columnIndex === 3 && tableId === 'tableCalls')) {
                        // For percentage or calls/s columns
                        const aBar = aCell.querySelector('.bar');
                        const bBar = bCell.querySelector('.bar');
                        aVal = aBar ? parseFloat(aBar.textContent) : 0;
                        bVal = bBar ? parseFloat(bBar.textContent) : 0;
                    } else {
                        // Regular number columns
                        aVal = parseFloat(aCell.textContent.replace(/,/g, '')) || 0;
                        bVal = parseFloat(bCell.textContent.replace(/,/g, '')) || 0;
                    }
                } else {
                    // String comparison
                    aVal = aCell.textContent.toLowerCase();
                    bVal = bCell.textContent.toLowerCase();
                }
                
                if (aVal < bVal) return ascending ? -1 : 1;
                if (aVal > bVal) return ascending ? 1 : -1;
                return 0;
            });
            
            // Re-append rows in sorted order
            rows.forEach(row => tbody.appendChild(row));
        }
    </script>
</body>
</html>
"""


def get_profile_stats(profile_file, top_n=50):
    """Extract statistics from a profile file."""
    p = pstats.Stats(profile_file)
    
    # Get basic stats
    stats_data = {
        'filename': os.path.basename(profile_file),
        'stats': {
            'total_calls': p.total_calls,
            'primitive_calls': p.prim_calls,
            'total_time': p.total_tt,
        },
        'cumulative': [],
        'tottime': [],
        'calls': []
    }
    
    # Extract top functions by cumulative time
    p.sort_stats('cumulative')
    stats_list = []
    for func, (cc, nc, tt, ct, callers) in list(p.stats.items())[:top_n]:
        stats_list.append({
            'function': f"{func[0]}:{func[1]}({func[2]})",
            'ncalls': nc,
            'tottime': tt,
            'percall_tot': tt / nc if nc else 0,
            'cumtime': ct,
            'percall_cum': ct / nc if nc else 0,
        })
    stats_data['cumulative'] = stats_list
    
    # Extract top functions by total time
    p.sort_stats('tottime')
    stats_list = []
    for func, (cc, nc, tt, ct, callers) in list(p.stats.items())[:top_n]:
        stats_list.append({
            'function': f"{func[0]}:{func[1]}({func[2]})",
            'ncalls': nc,
            'tottime': tt,
            'percall_tot': tt / nc if nc else 0,
            'cumtime': ct,
            'percall_cum': ct / nc if nc else 0,
        })
    stats_data['tottime'] = stats_list
    
    # Extract top functions by call count
    p.sort_stats('ncalls')
    stats_list = []
    for func, (cc, nc, tt, ct, callers) in list(p.stats.items())[:top_n]:
        stats_list.append({
            'function': f"{func[0]}:{func[1]}({func[2]})",
            'ncalls': nc,
            'tottime': tt,
            'cumtime': ct,
        })
    stats_data['calls'] = stats_list
    
    return stats_data



def analyze_profile(profile_file, top_n=30):
    """Analyze a single profile file."""
    print("\n" + "=" * 80)
    print(f"Analyzing: {os.path.basename(profile_file)}")
    print("=" * 80)
    
    p = pstats.Stats(profile_file)
    
    print("\n--- Top functions by CUMULATIVE time (including subcalls) ---")
    p.sort_stats('cumulative').print_stats(top_n)
    
    print("\n--- Top functions by TOTAL time (excluding subcalls) ---")
    p.sort_stats('tottime').print_stats(top_n)
    
    print("\n--- Functions from 'agents' module ---")
    p.sort_stats('cumulative').print_stats('agents')
    
    print("\n--- Functions from 'envs' module ---")
    p.sort_stats('cumulative').print_stats('envs')
    
    print("\n" + "=" * 80)


def get_latest_profile(profile_dir):
    """Get the most recent profile file."""
    profile_files = glob.glob(os.path.join(profile_dir, "*.prof"))
    if not profile_files:
        return None
    return max(profile_files, key=os.path.getctime)


def create_web_server(profile_dir, port=9999):
    """Create a Flask web server for interactive profile viewing."""
    app = Flask(__name__)
    
    @app.route('/')
    def index():
        return render_template_string(HTML_TEMPLATE)
    
    @app.route('/api/profiles')
    def list_profiles():
        """List all available profile files."""
        profile_files = glob.glob(os.path.join(profile_dir, "*.prof"))
        profiles = []
        
        for pf in sorted(profile_files, key=os.path.getctime, reverse=True):
            size = os.path.getsize(pf)
            size_str = f"{size / 1024:.1f} KB" if size < 1024 * 1024 else f"{size / (1024 * 1024):.1f} MB"
            profiles.append({
                'filename': os.path.basename(pf),
                'path': pf,
                'size': size_str,
                'modified': datetime.fromtimestamp(os.path.getctime(pf)).strftime('%Y-%m-%d %H:%M:%S')
            })
        
        return jsonify({'profiles': profiles})
    
    @app.route('/api/analyze')
    def analyze():
        """Analyze a specific profile file."""
        filename = request.args.get('filename')
        top_n = int(request.args.get('top_n', 50))
        
        if not filename:
            return jsonify({'error': 'No filename provided'}), 400
        
        profile_path = os.path.join(profile_dir, filename)
        
        if not os.path.exists(profile_path):
            return jsonify({'error': 'Profile file not found'}), 404
        
        try:
            stats = get_profile_stats(profile_path, top_n)
            return jsonify(stats)
        except Exception as e:
            return jsonify({'error': str(e)}), 500
    
    @app.route('/api/download')
    def download():
        """Download a profile file."""
        filename = request.args.get('filename')
        
        if not filename:
            return jsonify({'error': 'No filename provided'}), 400
        
        profile_path = os.path.join(profile_dir, filename)
        
        if not os.path.exists(profile_path):
            return jsonify({'error': 'Profile file not found'}), 404
        
        from flask import send_file
        return send_file(profile_path, as_attachment=True)
    
    return app


def open_browser(url, delay=1.5):
    """Open browser after a short delay."""
    time.sleep(delay)
    webbrowser.open(url)



def main():
    profile_dir = os.path.join(os.path.dirname(__file__), "profile_results")
    
    if not os.path.exists(profile_dir):
        print(f"Error: Profile directory '{profile_dir}' does not exist.")
        print("Run the app with ENABLE_PROFILING=true to generate profiles.")
        sys.exit(1)
    
    # Parse command line arguments
    console_mode = False
    port = 9999
    
    args = sys.argv[1:]
    
    # Check for flags
    if '--console' in args:
        console_mode = True
        args.remove('--console')
    
    if '--port' in args:
        port_idx = args.index('--port')
        if port_idx + 1 < len(args):
            port = int(args[port_idx + 1])
            args.pop(port_idx)  # Remove --port
            args.pop(port_idx)  # Remove port number
    
    # Console mode (old behavior)
    if console_mode:
        if '--all' in args or (len(args) > 0 and args[0] == '--all'):
            # Analyze all profiles
            profile_files = sorted(glob.glob(os.path.join(profile_dir, "*.prof")))
            if not profile_files:
                print("No profile files found.")
                sys.exit(1)
            
            for profile_file in profile_files:
                analyze_profile(profile_file, top_n=15)
        
        elif len(args) > 0 and args[0].endswith('.prof'):
            # Analyze specific profile
            profile_file = args[0]
            if not os.path.isabs(profile_file):
                profile_file = os.path.join(profile_dir, profile_file)
            
            if not os.path.exists(profile_file):
                print(f"Error: Profile file '{profile_file}' not found.")
                sys.exit(1)
            
            analyze_profile(profile_file)
        
        else:
            # Analyze most recent profile
            latest = get_latest_profile(profile_dir)
            if not latest:
                print("No profile files found.")
                print("Run the app with ENABLE_PROFILING=true to generate profiles.")
                sys.exit(1)
            
            analyze_profile(latest)
    
    else:
        # Web server mode (default)
        profile_files = glob.glob(os.path.join(profile_dir, "*.prof"))
        
        print("\n" + "=" * 70)
        print("🔥 Python Profile Viewer")
        print("=" * 70)
        print(f"\nProfile directory: {profile_dir}")
        print(f"Found {len(profile_files)} profile(s)")
        print(f"\nStarting web server at http://localhost:{port}")
        print("\nPress Ctrl+C to stop the server")
        print("=" * 70 + "\n")
        
        # Create and run the web server
        app = create_web_server(profile_dir, port)
        
        # Open browser in background thread
        url = f"http://localhost:{port}"
        threading.Thread(target=open_browser, args=(url,), daemon=True).start()
        
        try:
            app.run(host='0.0.0.0', port=port, debug=False)
        except KeyboardInterrupt:
            print("\n\nShutting down server...")
            sys.exit(0)


if __name__ == "__main__":
    main()
