# @package algorithm
# ^ tells hydra to place these value directly under algorithm key
ALG: meliba_ego
EGO_ACTOR_TYPE: mlp
NUM_EGO_TRAIN_SEEDS: 1
TOTAL_TIMESTEPS: 1e7
NUM_CHECKPOINTS: 5
NUM_ENVS: 8
LR: 7e-4 #3e-4
ENCODER_DECODER_LR: 0.001 #7e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.9
CLIP_EPS: 0.1
ENT_COEF: 0.2
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ANNEAL_LR: false

ENCODER_STATE_EMBED_DIM: 64
ENCODER_ACTION_EMBED_DIM: 64
ENCODER_REWARD_EMBED_DIM: 64
ENCODER_RNN_HIDDEN_DIM: 64
ENCODER_LAYERS_BEFORE_RNN: 64
ENCODER_LAYERS_AFTER_RNN: 64
ENCODER_LATENT_DIM: 64 # Latent dimension

DECODER_STATE_EMBED_DIM: 64
DECODER_AGENT_CHARACTER_EMBED_DIM: 32
DECODER_HIDDEN_DIM: 64
DECODER_OUTPUT_DIM: 32

DECODER_LOSS_COEFF: 1.0
DECODER_KL_WEIGHT: 0.05

partner_agent: # partner config for ppo_ego
  # Only specify ONE partner agent type. Must be RL-based.
  ippo: # Name of the partner agent type. Can be arbitrary.
    path: null # Please set the path to a partner agent checkpoint.
    actor_type: mlp # e.g. s5, rnn, mlp
    ckpt_key: final_params # Key to load from the checkpoint pytree.
    idx_list: [0] # list of checkpoint indices to load from the checkpoint pytree. If null, all checkpoints will be loaded.
