defaults:
  - reppo/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 6e6
TOTAL_TIMESTEPS_DECAY: 6e6
LR: 0.0003

GAMMA: 0.99
VMIN: -370 # -370 with step penalty, -300 without step penalty # Env dependent, (1 / (1 - gamma)) * min_reward
VMAX: 100 # Env dependent, (1 / (1 - gamma)) * max_reward

ANNEAL_LR: false
NUM_EPOCHS: 4

S5_D_MODEL: 128
S5_SSM_SIZE: 128
S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
FC_N_LAYERS: 3
