defaults:
  - cole/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS_PER_ITERATION: 6e6
PARTNER_POP_SIZE: 13
LR: 1e-3
UPDATE_EPOCHS: 15
CLIP_EPS: 0.05
ENT_COEF: 0.01
COLE_ALPHA: 0.1
C_UCT: 0.3
