# @package algorithm
# ^ tells hydra to place these value directly under algorithm key
ALG: lili_ego
ENCODER_TYPE: lstm
EGO_ACTOR_TYPE: mlp
NUM_EGO_TRAIN_SEEDS: 1
TOTAL_TIMESTEPS: 1e7
NUM_CHECKPOINTS: 5
NUM_ENVS: 8
LR: 3e-4
ENCODER_DECODER_LR: 7e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.05         # Do we keep this for LIAM?
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ANNEAL_LR: false

ENCODER_HIDDEN_DIM: 64
ENCODER_OUTPUT_DIM: 20 # Embedding dimension
DECODER_HIDDEN_DIM: 64
POLICY_INPUT_DIM: 20 # Embedding dimension + observation dimension (obs dim added in the run script)

partner_agent: # partner config for liam_ego
  name: lbf
  path: results/lbf/fcp/default_label/2025-07-16_23-22-45/saved_train_run #results/lbf/fcp/default_label/2025-06-06_21-43-40/saved_train_run 
  actor_type: mlp
  custom_loader:
  #  name:  # if null, use default loader
  #  type:  # options: ego, partner
  ckpt_key: final_params
  idx_list: [[0, -1]]
