defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS_PER_ITERATION: 2.05e7
PARTNER_POP_SIZE: 16
NUM_ENVS: 64
LR: 0.001
UPDATE_EPOCHS: 15
CLIP_EPS: 0.1
ENT_COEF: 0.03
COMEDI_ALPHA: 0.9 # Weight on the XP term.
COMEDI_BETA: 0.1 # Weight on the MP term.
ego_train_algorithm:
  TOTAL_TIMESTEPS: 6e7
  NUM_ENVS: 256
  LR: 1e-3
  ENT_COEF: 0.001
  CLIP_EPS: 0.1
