defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

PARTNER_POP_SIZE: 18
LR: 1e-3
UPDATE_EPOCHS: 15
CLIP_EPS: 0.01 # 0.1
ENT_COEF: 0.05
TOTAL_TIMESTEPS_PER_ITERATION: 1.82e7
ego_train_algorithm: 
  TOTAL_TIMESTEPS: 6e7
  LR: 1e-3
  ENT_COEF: 0.01
  CLIP_EPS: 0.05
