defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1.6e7
PARTNER_POP_SIZE: 20
LR: 1e-3
UPDATE_EPOCHS: 15
CLIP_EPS: 0.01 # 0.1
ENT_COEF: 0.05