defaults:
  - comedi/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS_PER_ITERATION: 9.17e6
PARTNER_POP_SIZE: 18
NUM_ENVS: 64
LR: 1e-4
UPDATE_EPOCHS: 15
CLIP_EPS: 0.5
ENT_COEF: 0.01
COMEDI_ALPHA: 0.4 # weight on XP return
COMEDI_BETA: 0.9 # weight on SXP return
ego_train_algorithm:
  TOTAL_TIMESTEPS: 3e7
  NUM_ENVS: 256
  LR: 1e-3
  ENT_COEF: 0.001
  CLIP_EPS: 0.5