# @package algorithm
# ^ tells hydra to place these value directly under algorithm key
ALG: ippo
TOTAL_TIMESTEPS: 5e5
ACTOR_TYPE: mlp
NUM_CHECKPOINTS: 5
GAMMA: 0.99
GAE_LAMBDA: 0.95
VF_COEF: 0.5
MAX_GRAD_NORM: 1.0
ANNEAL_LR: True
HUMAN_REG_COEF: 0.0
HUMAN_REG_MODE: none
HUMAN_REG_SCHEDULE: constant
HUMAN_REG_WARMUP_FRAC: 0.0
HUMAN_REG_RAMP_FRAC: 1.0
HUMAN_REF_BC_CHECKPOINT: null
HUMAN_REF_BC_CONFIG: null
