defaults:
  - oe_paired_comedi/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1.6e7 # per iter of open-ended training, divided between 4 types of rollouts and all partner seeds
TIMESTEPS_PER_ITER_EGO: 3e6
NUM_OPEN_ENDED_ITERS: 20
LR: 1e-3
NUM_MINIBATCHES: 8
CLIP_EPS: 0.1
ENT_COEF: 0.05